<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>apl</string>
	</array>
	<key>name</key>
	<string>APL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.single.begin.apl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String</string>
			<key>end</key>
			<string>'|
</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.single.end.apl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.newline.apl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.single.apl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.single.content.apl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Line comment</string>
			<key>match</key>
			<string>⍝.+</string>
			<key>name</key>
			<string>comment.line.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric constant</string>
			<key>match</key>
			<string>[0-9][0-9\.]*</string>
			<key>name</key>
			<string>constant.numeric.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Left Arrow - Assign</string>
			<key>match</key>
			<string>←</string>
			<key>name</key>
			<string>storage.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Open d-function/d-operator</string>
			<key>match</key>
			<string>{</string>
			<key>name</key>
			<string>support.function.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Close d-function/d-operator</string>
			<key>match</key>
			<string>}</string>
			<key>name</key>
			<string>support.function.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Rho - Shape/Reshape</string>
			<key>match</key>
			<string>⍴</string>
			<key>name</key>
			<string>storage.modifier.rho.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>High minus - Negate</string>
			<key>match</key>
			<string>¯</string>
			<key>name</key>
			<string>support.function.math.highminus.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Plus - Conjugate / Add</string>
			<key>match</key>
			<string>\+</string>
			<key>name</key>
			<string>support.function.math.plus.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Minus - Negate / Minus</string>
			<key>match</key>
			<string>-</string>
			<key>name</key>
			<string>support.function.math.minus.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Divide - Reciprocal / Divide</string>
			<key>match</key>
			<string>÷</string>
			<key>name</key>
			<string>support.function.math.divide.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Times - Sign Of / Multiply</string>
			<key>match</key>
			<string>×</string>
			<key>name</key>
			<string>support.function.math.times.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Stile - Magnitude / Residue</string>
			<key>match</key>
			<string>\|</string>
			<key>name</key>
			<string>support.function.math.stile.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Upstile - Ceiling / Maximum</string>
			<key>match</key>
			<string>⌈</string>
			<key>name</key>
			<string>support.function.math.upstile.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Downstile - Floor / Minimum</string>
			<key>match</key>
			<string>⌊</string>
			<key>name</key>
			<string>support.function.math.downstile.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Uptack - Decode</string>
			<key>match</key>
			<string>⊥</string>
			<key>name</key>
			<string>support.function.math.uptack.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Downtack - Encode</string>
			<key>match</key>
			<string>⊤</string>
			<key>name</key>
			<string>support.function.math.downtack.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Double alpha variable</string>
			<key>match</key>
			<string>⍺⍺</string>
			<key>name</key>
			<string>variable.parameter.doublealpha.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Alpha variable</string>
			<key>match</key>
			<string>⍺</string>
			<key>name</key>
			<string>variable.parameter.alpha.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Double Omega variable</string>
			<key>match</key>
			<string>⍵⍵</string>
			<key>name</key>
			<string>variable.parameter.doubleomega.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Omega variable</string>
			<key>match</key>
			<string>⍵</string>
			<key>name</key>
			<string>variable.parameter.omega.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Slash - reduce, first axis</string>
			<key>match</key>
			<string>/</string>
			<key>name</key>
			<string>keyword.operator.reduce.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Slash bar - reduce, last axis</string>
			<key>match</key>
			<string>⌿</string>
			<key>name</key>
			<string>keyword.operator.reducelast.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Backslash - scan, last axis</string>
			<key>match</key>
			<string>\\</string>
			<key>name</key>
			<string>keyword.operator.scan.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Backslash bar - scan, first axis</string>
			<key>match</key>
			<string>⍀</string>
			<key>name</key>
			<string>keyword.operator.scanlast.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Dot - inner product</string>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>keyword.operator.innerproduct.apl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Circle dot - outer product</string>
			<key>match</key>
			<string>∘\.</string>
			<key>name</key>
			<string>keyword.operator.outerproduct.apl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.apl</string>
	<key>uuid</key>
	<string>0d05b65e-3e85-4493-8936-fece72e43e47</string>
</dict>
</plist>
